/**
 * English strings — the source of truth for every other locale.
 *
 * Flat dotted keys keep the dictionaries comparable at a glance and make
 * `MessageKey` a plain union of literals, so a key missing from any other
 * locale is a compile error.
 *
 * Two kinds of placeholders exist in these strings:
 * - `{name}` filled by `t(key, { name: value })` — used for counts/values.
 * - `{token}` left in place for `segments()`, which splits the string so a
 *   component can render a link or a `<code>` element in the middle of it.
 */
const en = {
	'meta.description': 'VRChat Creator Companion package listing',

	'header.publishedBy': 'Published by',
	'header.learnMore': 'Learn more',
	'header.changeLanguage': 'Change language',

	'language.label': 'Language',
	'language.translatedBy': 'Translated by Deepseek V4.1 Flash',

	'common.listingUrl': 'Listing URL',
	'common.addToVcc': 'Add to VCC',
	'common.copy': 'Copy',
	'common.close': 'Close',
	'common.downloadZip': 'Download .ZIP',
	'common.viewOnGithub': 'View on GitHub',

	'bar.howToAdd': 'How do I add this to VCC?',

	'help.title': 'Adding this listing to VCC',
	'help.description': 'You only need to do this once.',
	'help.step1': 'Open VRChat Creator Companion (or ALCOM) and go to Settings → Packages.',
	'help.step2': 'Click “Add Repository”.',
	'help.step3': 'Paste the listing URL below into the field.',
	'help.step4': 'Click “Add”, then confirm the repository info with “I Understand”.',
	'help.step5': 'Open any project — packages from this listing now show up in Manage Packages.',
	'help.footer': 'Read more about package listings in the {link}.',
	'help.footerLink': 'VCC documentation',

	'panel.title': 'Packages',
	'panel.searchPlaceholder': 'Search name, id, keyword…',
	'panel.searchLabel': 'Search packages',
	'panel.filterAll': 'All',
	'panel.errorTitle': 'Could not load the package listing',
	'panel.errorHttp': 'Could not load {url} — HTTP {status}',
	'panel.errorJson': '{url} did not return JSON',
	'panel.errorHint':
		'{indexJson} is generated by the listing build — locally, run {fetch} to download the published one into {public}.',
	'panel.retry': 'Try again',
	'panel.emptyTitle': 'This listing has no packages yet',
	'panel.emptyHint': 'Releases published by the linked repositories will appear here automatically.',
	'panel.noMatchTitle': 'No packages match your filters',
	'panel.clearFilters': 'Clear filters',
	'panel.tablePackage': 'Package',
	'panel.tableType': 'Type',
	'panel.tableLatest': 'Latest',
	'panel.tableActions': 'Actions',
	'panel.versionCountOne': '{count} version',
	'panel.versionCountOther': '{count} versions',
	'panel.details': 'Package details',

	'type.avatar': 'Avatar',
	'type.world': 'World',
	'type.any': 'Any',

	'detail.packageFallback': 'Package',
	'detail.versions': 'Versions',
	'detail.author': 'Author',
	'detail.dependencies': 'Dependencies',
	'detail.none': 'None',
	'detail.unity': 'Unity',
	'detail.license': 'License',
	'detail.seeLicense': 'See license',
	'detail.sha256': 'SHA-256',
	'detail.copySha': 'Copy SHA-256',

	'toast.copiedToClipboard': 'Copied to clipboard',
	'toast.listingUrlCopied': 'Listing URL copied',
	'toast.shaCopied': 'SHA-256 copied',
	'toast.copyFailed': 'Could not copy'
} as const;

export default en;

export type MessageKey = keyof typeof en;
